import react from '@vitejs/plugin-react'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitest/config'

// Unit tests: everything external (axios, hooks, network) is mocked.
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { '@': fileURLToPath(new URL('.', import.meta.url)) },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./tests/support/setup.ts'],
    include: ['tests/unit/**/*.test.{ts,tsx}'],
    // Fixed values so the tests do not depend on the developer's .env file
    env: {
      VITE_API_BASE_URL: 'http://api.test',
      VITE_PAGE_SIZE: '100',
    },
    coverage: {
      provider: 'v8',
      reportsDirectory: './coverage',
      reporter: ['text', 'html', 'lcov', 'json-summary'],
      include: ['src/**/*.{ts,tsx}', 'components/layout/**/*.{ts,tsx}'],
      // Types only (no runtime code) and static assets
      exclude: ['src/types/**', 'src/assets/**'],
      // components/ui/** (generated by shadcn) and lib/utils.ts (a re-export) are outside "include"
      thresholds: { statements: 100, branches: 100, functions: 100, lines: 100 },
    },
  },
})
